Repository SoenCapstone/GameOn, pull requests merged in 2025-10, with the labels that each got.

#68 GO-8: Added CRUD operations to go-user-service
  GameOn-Backend/go-user-service/pom.xml
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/GoUserServiceApplication.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/controller/UserController.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/dto/DtoConstants.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/dto/UserRequest.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/dto/UserRequestCreate.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/dto/UserRequestUpdate.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/dto/UserResponse.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/exception/UserAlreadyExistsException.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/exception/UserNotFoundException.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/mapper/UserMapper.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/model/ErrorResponse.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/model/User.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/repository/UserRepository.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/service/UserService.java
  GameOn-Backend/go-user-service/src/main/java/com/game/on/go_user_service/utils/GlobalExceptionHandler.java
  GameOn-Backend/go-user-service/src/test/java/com/game/on/go_user_service/GoUserServiceApplicationTests.java
  GameOn-Backend/go-user-service/src/test/java/com/game/on/go_user_service/SmokeTest.java
  GameOn-Backend/go-user-service/src/test/java/com/game/on/go_user_service/UserServiceTest.java
Labels: F1 - Account Creation

#70 Fixed SonarQube issues introduced by initial frontend setup
  GameOn-Frontend/app/(tabs)/_layout.tsx
  GameOn-Frontend/components/ui/icon-symbol.ios.tsx
  GameOn-Frontend/components/ui/icon-symbol.tsx
  GameOn-Frontend/package-lock.json
  GameOn-Frontend/package.json
  GameOn-Frontend/scripts/reset-project.js
Labels: task

#71 Login and Sign-up UX polish: DOB wheel picker, success notification/log, warning fixes
  GameOn-Frontend/__tests__/sign-up.test.tsx
  GameOn-Frontend/app/(auth)/sign-in.tsx
  GameOn-Frontend/app/(auth)/sign-up.tsx
  GameOn-Frontend/constants/auth-layout.ts
  GameOn-Frontend/constants/auth-styles.ts
  GameOn-Frontend/contexts/auth.tsx
  GameOn-Frontend/package-lock.json
  GameOn-Frontend/package.json
Labels: bug, F1 - Account Creation
